# Generated by Django 3.2.18 on 2023-04-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='Choice',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
    ]
