# Generated by Django 3.2.18 on 2023-04-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_resource_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='service_id',
            new_name='service',
        ),
    ]
